import{i as l,S as g,a as y}from"./assets/vendor-BG8zX51N.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const o of t)if(o.type==="childList")for(const m of o.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&r(m)}).observe(document,{childList:!0,subtree:!0});function a(t){const o={};return t.integrity&&(o.integrity=t.integrity),t.referrerPolicy&&(o.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?o.credentials="include":t.crossOrigin==="anonymous"?o.credentials="omit":o.credentials="same-origin",o}function r(t){if(t.ep)return;t.ep=!0;const o=a(t);fetch(t.href,o)}})();const v=async(s,e,a)=>await e.get("https://pixabay.com/api/",{params:{key:"48259740-4b53b0822f94ea1fa118abb4f",q:s,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:a}}),L=(s,e)=>{s.innerHTML="",e.show({message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"#fafafb",backgroundColor:"#ef4040",image:"../img/error.png",imageWidth:24,zindex:99999,position:"topRight",maxWidth:"432px",overlayColor:"#b51b1b"})},b=(s,e)=>{const a=s.map(r=>`<li class="elementOfGallery">
            <div class="imageOfElement">
              <a
                href="${r.largeImageURL}"
                ><img
                  src="${r.webformatURL}"
                  alt="${r.tags}"
              /></a>
              <div class="infoOfElement">
                <p><span>Likes </span> ${r.likes}</p>
                <p><span>Views </span> ${r.views}</p>
                <p><span>Comments </span> ${r.comments}</p>
                <p><span>Downloads </span> ${r.downloads}</p>
              </div>
            </div>
          </li>`).join("");e.insertAdjacentHTML("beforeend",a)},C=document.querySelector(".searchInput");document.querySelector(".submitBtn");const h=document.querySelector(".mainForm"),d=document.querySelector(".gallery"),u=document.querySelector(".loader"),i=document.querySelector(".btnLoadMore");let p,c="",n=1,f;h.addEventListener("submit",s=>{if(s.preventDefault(),c=C.value,c.trim()===""){l.show({message:"There must be smth!",messageColor:"#fafafb",backgroundColor:"#ef4040",position:"topCenter",overlayColor:"#b51b1b"});return}else i.classList.add("visually-hidden"),d.innerHTML="",n=1,u.classList.remove("visually-hidden"),v(c,y,n).then(e=>{u.classList.add("visually-hidden"),i.classList.remove("visually-hidden");const{hits:a}=e.data;a.length===0?(L(d,l),i.classList.add("visually-hidden")):(b(a,d),new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),e.data.totalHits<=n*15&&(i.classList.add("visually-hidden"),l.show({message:"We are sorry, but you have reached the end of search results.",messageColor:"#000000",backgroundColor:"#1e99e6",position:"center",overlayColor:"#004b7a"})))}).catch(e=>l.show({title:"Sorry!",titleColor:"#fafafb",message:"Something went wrong!",messageColor:"#fafafb",backgroundColor:"#db9e02",position:"center",overlayColor:"#996e00"}));h.reset()});i.addEventListener("click",s=>{s.preventDefault(),n+=1,p=document.querySelector(".elementOfGallery"),f=3*p.getBoundingClientRect().height,console.log(f),i.classList.add("visually-hidden"),u.classList.remove("visually-hidden"),v(c,y,n).then(e=>{u.classList.add("visually-hidden"),i.classList.remove("visually-hidden");const{hits:a}=e.data;b(a,d),new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),setTimeout(()=>{window.scrollBy({top:f,behavior:"smooth"})},100),e.data.totalHits<=n*15&&(i.classList.add("visually-hidden"),l.show({message:"We are sorry, but you have reached the end of search results.",messageColor:"#000000",backgroundColor:"#1e99e6",position:"center",overlayColor:"#004b7a"}))}).catch(e=>l.show({title:"Sorry!",titleColor:"#fafafb",message:"Something went wrong!",messageColor:"#fafafb",backgroundColor:"#db9e02",position:"center",overlayColor:"#996e00"}))});
//# sourceMappingURL=index.js.map
