import{i as n,S as g,a as y}from"./assets/vendor-BG8zX51N.js";(function(){const e=document.createElement("link").relList;if(e&&e.supports&&e.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))r(t);new MutationObserver(t=>{for(const s of t)if(s.type==="childList")for(const m of s.addedNodes)m.tagName==="LINK"&&m.rel==="modulepreload"&&r(m)}).observe(document,{childList:!0,subtree:!0});function o(t){const s={};return t.integrity&&(s.integrity=t.integrity),t.referrerPolicy&&(s.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?s.credentials="include":t.crossOrigin==="anonymous"?s.credentials="omit":s.credentials="same-origin",s}function r(t){if(t.ep)return;t.ep=!0;const s=o(t);fetch(t.href,s)}})();const v=async(a,e,o)=>await e.get("https://pixabay.com/api/",{params:{key:"48259740-4b53b0822f94ea1fa118abb4f",q:a,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15,page:o}}),L=(a,e)=>{a.innerHTML="",e.show({message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"#fafafb",backgroundColor:"#ef4040",image:"../img/error.png",imageWidth:24,zindex:99999,position:"topRight",maxWidth:"432px",overlayColor:"#b51b1b"})},b=(a,e)=>{const o=a.map(r=>`<li class="elementOfGallery">
            <div class="imageOfElement">
              <a
                href="${r.largeImageURL}"
                ><img
                  src="${r.webformatURL}"
                  alt="${r.tags}"
              /></a>
              <div class="infoOfElement">
                <p><span>Likes </span> ${r.likes}</p>
                <p><span>Views </span> ${r.views}</p>
                <p><span>Comments </span> ${r.comments}</p>
                <p><span>Downloads </span> ${r.downloads}</p>
              </div>
            </div>
          </li>`).join("");e.insertAdjacentHTML("beforeend",o)},C=document.querySelector(".searchInput");document.querySelector(".submitBtn");const f=document.querySelector(".mainForm"),d=document.querySelector(".gallery"),u=document.querySelector(".loader"),i=document.querySelector(".btnLoadMore");let h,c="",l=1,p;f.addEventListener("submit",a=>{if(a.preventDefault(),c=C.value,c.trim()===""){n.show({message:"There must be smth!",messageColor:"#fafafb",backgroundColor:"#ef4040",position:"topCenter",overlayColor:"#b51b1b"});return}else i.classList.add("visually-hidden"),d.innerHTML="",l=1,u.classList.remove("visually-hidden"),v(c,y,l).then(e=>{u.classList.add("visually-hidden"),i.classList.remove("visually-hidden");const{hits:o}=e.data;o.length===0?(L(d,n),i.classList.add("visually-hidden")):(b(o,d),new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),e.data.totalHits<=l*15&&(i.classList.add("visually-hidden"),n.show({message:"We are sorry, but you have reached the end of search results.",messageColor:"#000000",backgroundColor:"#1e99e6",position:"center",overlayColor:"#004b7a"})))}).catch(e=>n.show({title:"Sorry!",titleColor:"#fafafb",message:"Something went wrong!",messageColor:"#fafafb",backgroundColor:"#db9e02",position:"center",overlayColor:"#996e00"}));f.reset()});i.addEventListener("click",a=>{a.preventDefault(),l+=1,h=document.querySelector(".elementOfGallery"),p=3*h.getBoundingClientRect().height,i.classList.add("visually-hidden"),u.classList.remove("visually-hidden"),v(c,y,l).then(e=>{u.classList.add("visually-hidden"),i.classList.remove("visually-hidden");const{hits:o}=e.data;b(o,d),new g(".gallery a",{captionsData:"alt",captionDelay:250}).refresh(),setTimeout(()=>{window.scrollBy({top:p,behavior:"smooth"})},100),e.data.totalHits<=l*15&&(i.classList.add("visually-hidden"),n.show({message:"We are sorry, but you have reached the end of search results.",messageColor:"#000000",backgroundColor:"#1e99e6",position:"center",overlayColor:"#004b7a"}))}).catch(e=>n.show({title:"Sorry!",titleColor:"#fafafb",message:"Something went wrong!",messageColor:"#fafafb",backgroundColor:"#db9e02",position:"center",overlayColor:"#996e00"}))});
//# sourceMappingURL=index.js.map
